/* My cheat sheet for making these 

EXCEL:
\"@\"

POWESHELL:
(get-content ".csv") | foreach {"[" + $_ } 
(get-content ".csv") | foreach { $_ + "]," } 


VERBS, tenses up here, lists for classes down there. 
First row col 1 is tense name, in the rest of the cols
Rest of the arrays are infinitif followed by conjugated 
verbs matching the pronounds in the first row
*/
var present = [
    ["présent","empty","je","tu","il / elle/ on","nous","vous","ils / elles"],
    ["abandonner","to abandon","abandonne","abandonnes","abandonne","abandonnons","abandonnez","abandonnent"],
    ["acheter","to buy","achète","achètes","achète","achetons","achetez","achètent"],
    ["admirer","to admire","admire","admires","admire","admirons","admirez","admirent"],
    ["adorer","to adore","adore","adores","adore","adorons","adorez","adorent"],
    ["aider","to help","aide","aides","aide","aidons","aidez","aident"],
    ["aimer","to like, love","aime","aimes","aime","aimons","aimez","aiment"],
    ["ajouter","to add","ajoute","ajoutes","ajoute","ajoutons","ajoutez","ajoutent"],
    ["appeler","to call","appelle","appelles","appelle","appelons","appelez","appellent"],
    ["apporter","to bring","apporte","apportes","apporte","apportons","apportez","apportent"],
    ["arriver","to arrive","arrive","arrives","arrive","arrivons","arrivez","arrivent"],
    ["attraper","to catch","attrape","attrapes","attrape","attrapons","attrapez","attrapent"],
    ["augmenter","to increase","augmente","augmentes","augmente","augmentons","augmentez","augmentent"],
    ["bouger","to move","bouge","bouges","bouge","bougeons","bougez","bougent"],
    ["camper","to camp","campe","campes","campe","campons","campez","campent"],
    ["changer","to change","change","changes","change","changeons","changez","changent"],
    ["chanter","to sing","chante","chantes","chante","chantons","chantez","chantent"],
    ["chercher","to look for","cherche","cherches","cherche","cherchons","cherchez","cherchent"],
    ["commander","to order","commande","commandes","commande","commandons","commandez","commandent"],
    ["compter","to count","compte","comptes","compte","comptons","comptez","comptent"],
    ["consulter","to consult","consulte","consultes","consulte","consultons","consultez","consultent"],
    ["continuer","to continue","continue","continues","continue","continuons","continuez","continuent"],
    ["couper","to cut","coupe","coupes","coupe","coupons","coupez","coupent"],
    ["créer","to create","crée","crées","crée","créons","créez","créent"],
    ["danser","to dance","danse","danses","danse","dansons","dansez","dansent"],
    ["décider","to decide","décide","décides","décide","décidons","décidez","décident"],
    ["détester","to hate","déteste","détestes","déteste","détestons","détestez","détestent"],
    ["diminuer","to decrease","diminue","diminues","diminue","diminuons","diminuez","diminuent"],
    ["dîner","to dine","dîne","dînes","dîne","dînons","dînez","dînent"],
    ["donner","to give","donne","donnes","donne","donnons","donnez","donnent"],
    ["échanger","to exchange","échange","échanges","échange","échangeons","échangez","échangent"],
    ["écouter","to listen","écoute","écoutes","écoute","écoutons","écoutez","écoutent"],
    ["embaucher","to hire","embauche","embauches","embauche","embauchons","embauchez","embauchent"],
    ["embrasser","to kiss","embrasse","embrasses","embrasse","embrassons","embrassez","embrassent"],
    ["emmener","to take someone","emmène","emmènes","emmène","emmenons","emmenez","emmènent"],
    ["emprunter","to borrow","emprunte","empruntes","emprunte","empruntons","empruntez","empruntent"],
    ["enseigner","to teach","enseigne","enseignes","enseigne","enseignons","enseignez","enseignent"],
    ["entrer","to enter","entre","entres","entre","entrons","entrez","entrent"],
    ["essayer","to try","essaie","essaies","essaie","essayons","essayez","essaient"],
    ["étudier","to study","étudie","étudies","étudie","étudions","étudiez","étudient"],
    ["éviter","to avoid","évite","évites","évite","évitons","évitez","évitent"],
    ["exiger","to demand","exige","exiges","exige","exigeons","exigez","exigent"],
    ["expliquer","to explain","explique","expliques","explique","expliquons","expliquez","expliquent"],
    ["fermer","to close","ferme","fermes","ferme","fermons","fermez","ferment"],
    ["garder","to keep","garde","gardes","garde","gardons","gardez","gardent"],
    ["habiter","to live","habite","habites","habite","habitons","habitez","habitent"],
    ["indiquer","to indicate","indique","indiques","indique","indiquons","indiquez","indiquent"],
    ["inviter","to invite","invite","invites","invite","invitons","invitez","invitent"],
    ["jouer","to play","joue","joues","joue","jouons","jouez","jouent"],
    ["laisser","to leave, to let","laisse","laisses","laisse","laissons","laissez","laissent"],
    ["laver","to wash","lave","laves","lave","lavons","lavez","lavent"],
    ["louer","to rent","loue","loues","loue","louons","louez","louent"],
    ["manger","to eat","mange","manges","mange","mangeons","mangez","mangent"],
    ["marcher","to walk","marche","marches","marche","marchons","marchez","marchent"],
    ["monter","to go up","monte","montes","monte","montons","montez","montent"],
    ["nager","to swim","nage","nages","nage","nageons","nagez","nagent"],
    ["naviguer","to navigate","navigue","navigues","navigue","naviguons","naviguez","naviguent"],
    ["nettoyer","to clean","nettoie","nettoies","nettoie","nettoyons","nettoyez","nettoient"],
    ["organiser","to organise","organise","organises","organise","organisons","organisez","organisent"],
    ["oublier","to forget","oublie","oublies","oublie","oublions","oubliez","oublient"],
    ["parler","to speak","parle","parles","parle","parlons","parlez","parlent"],
    ["partager","to share","partage","partages","partage","partageons","partagez","partagent"],
    ["passer","to pass, spend time","passe","passes","passe","passons","passez","passent"],
    ["penser","to think","pense","penses","pense","pensons","pensez","pensent"],
    ["posséder","to own","possède","possèdes","possède","possédons","possédez","possèdent"],
    ["préférer","to prefer","préfère","préfères","préfère","préférons","préférez","préfèrent"],
    ["préparer","to prepare","prépare","prépares","prépare","préparons","préparez","préparent"],
    ["profiter","to enjoy, to profit","profite","profites","profite","profitons","profitez","profitent"],
    ["proposer","to propose","propose","proposes","propose","proposons","proposez","proposent"],
    ["quitter","to leave someone or something","quitte","quittes","quitte","quittons","quittez","quittent"],
    ["ranger","to put away, to clean up","range","ranges","range","rangeons","rangez","rangent"],
    ["réaliser","to achieve,  to understand","réalise","réalises","réalise","réalisons","réalisez","réalisent"],
    ["remercier","to thank","remercie","remercies","remercie","remercions","remerciez","remercient"],
    ["rentrer","to go back in","rentre","rentres","rentre","rentrons","rentrez","rentrent"],
    ["repousser","to postpone, to push away","repousse","repousses","repousse","repoussons","repoussez","repoussent"],
    ["réserver","to book","réserve","réserves","réserve","réservons","réservez","réservent"],
    ["respecter","to respect","respecte","respectes","respecte","respectons","respectez","respectent"],
    ["rester","to stay","reste","restes","reste","restons","restez","restent"],
    ["retourner","to go back","retourne","retournes","retourne","retournons","retournez","retournent"],
    ["simplifier","to simplify","simplifie","simplifies","simplifie","simplifions","simplifiez","simplifient"],
    ["téléphoner","to call on the phone","téléphone","téléphones","téléphone","téléphonons","téléphonez","téléphonent"],
    ["tomber","to fall","tombe","tombes","tombe","tombons","tombez","tombent"],
    ["tourner","to turn","tourne","tournes","tourne","tournons","tournez","tournent"],
    ["travailler","to work","travaille","travailles","travaille","travaillons","travaillez","travaillent"],
    ["traverser","to cross","traverse","traverses","traverse","traversons","traversez","traversent"],
    ["trouver","to find","trouve","trouves","trouve","trouvons","trouvez","trouvent"],
    ["vider","to empty","vide","vides","vide","vidons","videz","vident"],
    ["voyager","to travel","voyage","voyages","voyage","voyageons","voyagez","voyagent"],
    ["accomplir","to accomplish","accomplis","accomplis","accomplit","accomplissons","accomplissez","accomplissent"],
    ["agir","to act","agis","agis","agit","agissons","agissez","agissent"],
    ["avertir","to warn","avertis","avertis","avertit","avertissons","avertissez","avertissent"],
    ["choisir","to choose","choisis","choisis","choisit","choisissons","choisissez","choisissent"],
    ["finir","to finish","finis","finis","finit","finissons","finissez","finissent"],
    ["grandir","to grow","grandis","grandis","grandit","grandissons","grandissez","grandissent"],
    ["grossir","to get bigger","grossis","grossis","grossit","grossissons","grossissez","grossissent"],
    ["guérir","to heal","guéris","guéris","guérit","guérissons","guérissez","guérissent"],
    ["maigrir","to loose weight","maigris","maigris","maigrit","maigrissons","maigrissez","maigrissent"],
    ["obéir","to obey","obéis","obéis","obéit","obéissons","obéissez","obéissent"],
    ["réagir","to react","réagis","réagis","réagit","réagissons","réagissez","réagissent"],
    ["réfléchir","to think, reflect","réfléchis","réfléchis","réfléchit","réfléchissons","réfléchissez","réfléchissent"],
    ["refroidir","to cool down","refroidis","refroidis","refroidit","refroidissons","refroidissez","refroidissent"],
    ["remplir","to fill","remplis","remplis","remplit","remplissons","remplissez","remplissent"],
    ["réussir","to succeed","réussis","réussis","réussit","réussissons","réussissez","réussissent"],
    ["rougir","to turn red, blush","rougis","rougis","rougit","rougissons","rougissez","rougissent"],
    ["vieillir","to get older","vieillis","vieillis","vieillit","vieillissons","vieillissez","vieillissent"],
    ["admettre","to admit","admets","admets","admet","admettons","admettez","admettent"],
    ["aller","to go","vais","vas","va","allons","allez","vont"],
    ["attendre","to wait","attends","attends","attend","attendons","attendez","attendent"],
    ["avoir","to have","ai","as","a","avons","avez","ont"],
    ["boire","to drink","bois","bois","boit","buvons","buvez","boivent"],
    ["commettre","to commit","commets","commets","commet","commettons","commettez","commettent"],
    ["comprendre","to understand","comprends","comprends","comprend","comprenons","comprenez","comprennent"],
    ["connaître","to know something","connais","connais","connaît","connaissons","connaissez","connaissent"],
    ["croire","to believe","crois","crois","croit","croyons","croyez","croient"],
    ["défendre","to defend, forbid","défends","défends","défend","défendons","défendez","défendent"],
    ["descendre","to go down","descends","descends","descend","descendons","descendez","descendent"],
    ["devenir","to become","deviens","deviens","devient","devenons","devenez","deviennent"],
    ["devoir","to have to","dois","dois","doit","devons","devez","doivent"],
    ["dormir","to sleep","dors","dors","dort","dormons","dormez","dorment"],
    ["écrire","to write","écris","écris","écrit","écrivons","écrivez","écrivent"],
    ["entendre","to hear","entends","entends","entend","entendons","entendez","entendent"],
    ["envoyer","to send","envoie","envoies","envoie","envoyons","envoyez","envoient"],
    ["espérer","to hope","espère","espères","espère","espérons","espérez","espèrent"],
    ["être","to be","suis","es","est","sommes","êtes","sont"],
    ["faire","to do","fais","fais","fait","faisons","faites","font"],
    ["mettre","to set, to put on","mets","mets","met","mettons","mettez","mettent"],
    ["mourir","to die","meurs","meurs","meurt","mourons","mourez","meurent"],
    ["naître","to be born","nais","nais","naît","naissons","naissez","naissent"],
    ["partir","to leave","pars","pars","part","partons","partez","partent"],
    ["perdre","to loose","perds","perds","perd","perdons","perdez","perdent"],
    ["permettre","to allow","permets","permets","permet","permettons","permettez","permettent"],
    ["pouvoir","to be able to","peux","peux","peut","pouvons","pouvez","peuvent"],
    ["prendre","to take","prends","prends","prend","prenons","prenez","prennent"],
    ["promettre","to promise","promets","promets","promet","promettons","promettez","promettent"],
    ["remettre","to postpone","remets","remets","remet","remettons","remettez","remettent"],
    ["rendre","to give back","rends","rends","rend","rendons","rendez","rendent"],
    ["répondre","to answer","réponds","réponds","répond","répondons","répondez","répondent"],
    ["revenir","to come back","reviens","reviens","revient","revenons","revenez","reviennent"],
    ["rire","to laugh","ris","ris","rit","rions","riez","rient"],
    ["savoir","to know how to","sais","sais","sait","savons","savez","savent"],
    ["sortir","to go out","sors","sors","sort","sortons","sortez","sortent"],
    ["sourire","to smile","souris","souris","sourit","sourions","souriez","sourient"],
    ["suivre","to follow","suis","suis","suit","suivons","suivez","suivent"],
    ["vendre","to sell","vends","vends","vend","vendons","vendez","vendent"],
    ["venir","to come","viens","viens","vient","venons","venez","viennent"],
    ["vouloir","to want","veux","veux","veut","voulons","voulez","veulent"],
    [" s'habiller","to get dressed","m'habille","t'habilles","s'habille","nous habillons","vous habillez","s'habillent"],
    ["s'aimer","to love each other","m'aime","t'aimes","s'aime","nous aimons","vous aimez","s'aiment"],
    ["s'amuser","to have fun","m'amuse","t'amuses","s'amuse","nous amusons","vous amusez","s'amusent"],
    ["s'appeler","to be named","m'appelle","t'appelles","s'appelle","nous appelons","vous appelez","s'appellent"],
    ["s'arrêter","to stop","m'arrête","t'arrêtes","s'arrête","nous arrêtons","vous arrêtez","s'arrêtent"],
    ["se brosser","to brush","me brosse","te brosses","se brosse","nous brossons","vous brossez","se brossent"],
    ["se confier","to confide","me confie","te confies","se confie","nous confions","vous confiez","se confient"],
    ["se coucher","to go to bed","me couche","te couches","se couche","nous couchons","vous couchez","se couchent"],
    ["se débrouiller","to manage","me débrouille","te débrouilles","se débrouille","nous débrouillons","vous débrouillez","se débrouillent"],
    ["se dépêcher","to hurry","me dépêche","te dépêches","se dépêche","nous dépêchons","vous dépêchez","se dépêchent"],
    ["se détendre","to relax","me détends","te détends","se détend","nous détendons","vous détendez","se détendent"],
    ["se disputer","to argue","me dispute","te disputes","se dispute","nous disputons","vous disputez","se disputent"],
    ["se fâcher","to get angry","me fâche","te fâches","se fâche","nous fâchons","vous fâchez","se fâchent"],
    ["se fiancer","to get engaged","me fiance","te fiances","se fiance","nous fiançons","vous fiancez","se fiancent"],
    ["se laver ","to wash","me lave","tu te laves","se lave","nous lavons","vous lavez","se lavent"],
    ["se lever","to get up","me lève","te lèves","se lève","nous levons","vous levez","se lèvent"],
    ["se marier","to get married","me marie","te maries","se marie","nous marions","vous mariez","se marient"],
    ["se méfier","to distrust","me méfie","te méfies","se méfie","nous méfions","vous méfiez","se méfient"],
    ["se passer","to do without","me passe","te passes","se passe","nous passons","vous passez","se passent"],
    ["se peigner","to comb","me peigne","te peignes","se peigne","nous peignons","vous peignez","se peignent"],
    ["se préparer","to get ready","me prépare","te prépares","se prépare","nous préparons","vous préparez","se préparent"],
    ["se rappeler","to recall","me rappelle","te rappelles","se rappelle","nous rappelons","vous rappelez","se rappellent"],
    ["se raser","to shave","me rase","te rases","se rase","nous rasons","vous rasez","se rasent"],
    ["se reposer","to relax","me repose","te reposes","se repose","nous reposons","vous reposez","se reposent"],
    ["se réveiller","to wake up","me réveille","te réveilles","se réveille","nous réveillons","vous réveillez","se réveillent"],
    ["se sentir","to feel","me sens","te sens","se sent","nous sentons","vous sentez","se sentent"],
    ["se souvenir","to remember","me souviens","te souviens","se souvient","nous souvenons","vous souvenez","se souviennent"],
    ["s'embrasser","to kiss ","m'embrasse","t'embrasses","s'embrasse","nous embrassons","vous embrassez","s'embrassent"],
    ["s'entendre","to get along","m'entends","t'entends","s'entend","nous entendons","vous entendez","s'entendent"],
    ["s'habituer","to get used to","m'habitue","t'habitues","s'habitue","nous habituons","vous habituez","s'habituent"],
    ["s'intéresser","to be interested in","m'intéresse","t'intéresses","s'intéresse","nous intéressons","vous intéressez","s'intéressent"],
    ["s'occuper","to take care of","m'occupe","t'occupes","s'occupe","nous occupons","vous occupez","s'occupent"]
]

var imparfait = [
    ["imparfait","empty","je","tu","il / elle/ on","nous","vous","ils / elles"],
    ["abandonner","to abandon","abandonnais","abandonnais","abandonnait","abandonnions","abandonniez","abandonnaient"],
    ["acheter","to buy","achetais","achetais","achetait","achetions","achetiez","achetaient"],
    ["admirer","to admire","admirais","admirais","admirait","admirions","admiriez","admiraient"],
    ["adorer","to adore","adorais","adorais","adorait","adorions","adoriez","adoraient"],
    ["aider","to help","aidais","aidais","aidait","aidions","aidiez","aidaient"],
    ["aimer","to like, love","aimais","aimais","aimait","aimions","aimiez","aimaient"],
    ["ajouter","to add","ajoutais","ajoutais","ajoutait","ajoutions","ajoutiez","ajoutaient"],
    ["appeler","to call","appelais","appelais","appelait","appelions","appeliez","appelaient"],
    ["apporter","to bring","apportais","apportais","apportait","apportions","apportiez","apportaient"],
    ["arriver","to arrive","arrivais","arrivais","arrivait","arrivions","arriviez","arrivaient"],
    ["attraper","to catch","attrapais","attrapais","attrapait","attrapions","attrapiez","attrapaient"],
    ["augmenter","to increase","augmentais","augmentais","augmentait","augmentions","augmentiez","augmentaient"],
    ["bouger","to move","bougeais","bougeais","bougeait","bougions","bougiez","bougeaient"],
    ["camper","to camp","campais","campais","campait","campions","campiez","campaient"],
    ["changer","to change","changeais","changeais","changeait","changions","changiez","changeaient"],
    ["chanter","to sing","chantais","chantais","chantait","chantions","chantiez","chantaient"],
    ["chercher","to look for","cherchais","cherchais","cherchait","cherchions","cherchiez","cherchaient"],
    ["commander","to order","commandais","commandais","commandait","commandions","commandiez","commandaient"],
    ["compter","to count","comptais","comptais","comptait","comptions","comptiez","comptaient"],
    ["consulter","to consult","consultais","consultais","consultait","consultions","consultiez","consultaient"],
    ["continuer","to continue","continuais","continuais","continuait","continuions","continuiez","continuaient"],
    ["couper","to cut","coupais","coupais","coupait","coupions","coupiez","coupaient"],
    ["créer","to create","créais","créais","créait","créions","créiez","créaient"],
    ["danser","to dance","dansais","dansais","dansait","dansions","dansiez","dansaient"],
    ["décider","to decide","décidais","décidais","décidait","décidions","décidiez","décidaient"],
    ["détester","to hate","détestais","détestais","détestait","détestions","détestiez","détestaient"],
    ["diminuer","to decrease","diminuais","diminuais","diminuait","diminuions","diminuiez","diminuaient"],
    ["dîner","to dine","dînais","dînais","dînait","dînions","dîniez","dînaient"],
    ["donner","to give","donnais","donnais","donnait","donnions","donniez","donnaient"],
    ["échanger","to exchange","échangeais","échangeais","échangeait","échangions","échangiez","échangeaient"],
    ["écouter","to listen","écoutais","écoutais","écoutait","écoutions","écoutiez","écoutaient"],
    ["embaucher","to hire","embauchais","embauchais","embauchait","embauchions","embauchiez","embauchaient"],
    ["embrasser","to kiss","embrassais","embrassais","embrassait","embrassions","embrassiez","embrassaient"],
    ["emmener","to take someone","emmenais","emmenais","emmenait","emmenions","emmeniez","emmenaient"],
    ["emprunter","to borrow","empruntais","empruntais","empruntait","empruntions","empruntiez","empruntaient"],
    ["enseigner","to teach","enseignais","enseignais","enseignait","enseignions","enseigniez","enseignaient"],
    ["entrer","to enter","entrais","entrais","entrait","entrions","entriez","entraient"],
    ["essayer","to try","essayais","essayais","essayait","essayions","essayiez","essayaient"],
    ["étudier","to study","étudiais","étudiais","étudiait","étudiions","étudiiez","étudiaient"],
    ["éviter","to avoid","évitais","évitais","évitait","évitions","évitiez","évitaient"],
    ["exiger","to demand","exigeais","exigeais","exigeait","exigions","exigiez","exigeaient"],
    ["expliquer","to explain","expliquais","expliquais","expliquait","expliquions","expliquiez","expliquaient"],
    ["fermer","to close","fermais","fermais","fermait","fermions","fermiez","fermaient"],
    ["garder","to keep","gardais","gardais","gardait","gardions","gardiez","gardaient"],
    ["habiter","to live","habitais","habitais","habitait","habitions","habitiez","habitaient"],
    ["indiquer","to indicate","indiquais","indiquais","indiquait","indiquions","indiquiez","indiquaient"],
    ["inviter","to invite","invitais","invitais","invitait","invitions","invitiez","invitaient"],
    ["jouer","to play","jouais","jouais","jouait","jouions","jouiez","jouaient"],
    ["laisser","to leave, to let","laissais","laissais","laissait","laissions","laissiez","laissaient"],
    ["laver","to wash","lavais","lavais","lavait","lavions","laviez","lavaient"],
    ["louer","to rent","louais","louais","louait","louions","louiez","louaient"],
    ["manger","to eat","mangeais","mangeais","mangeait","mangions","mangiez","mangeaient"],
    ["marcher","to walk","marchais","marchais","marchait","marchions","marchiez","marchaient"],
    ["monter","to go up","montais","montais","montait","montions","montiez","montaient"],
    ["nager","to swim","nageais","nageais","nageait","nagions","nagiez","nageaient"],
    ["naviguer","to navigate","naviguais","naviguais","naviguait","naviguions","naviguiez","naviguaient"],
    ["nettoyer","to clean","nettoyais","nettoyais","nettoyait","nettoyions","nettoyiez","nettoyaient"],
    ["organiser","to organise","organisais","organisais","organisait","organisions","organisiez","organisaient"],
    ["oublier","to forget","oubliais","oubliais","oubliait","oubliions","oubliiez","oubliaient"],
    ["parler","to speak","parlais","parlais","parlait","parlions","parliez","parlaient"],
    ["partager","to share","partageais","partageais","partageait","partagions","partagiez","partageaient"],
    ["passer","to pass, spend time","passais","passais","passait","passions","passiez","passaient"],
    ["penser","to think","pensais","pensais","pensait","pensions","pensiez","pensaient"],
    ["posséder","to own","possédais","possédais","possédait","possédions","possédiez","possédaient"],
    ["préférer","to prefer","préférais","préférais","préférait","préférions","préfériez","préféraient"],
    ["préparer","to prepare","préparais","préparais","préparait","préparions","prépariez","préparaient"],
    ["profiter","to enjoy, to profit","profitais","profitais","profitait","profitions","profitiez","profitaient"],
    ["proposer","to propose","proposais","proposais","proposait","proposions","proposiez","proposaient"],
    ["quitter","to leave someone or something","quittais","quittais","quittait","quittions","quittiez","quittaient"],
    ["ranger","to put away, to clean up","rangeais","rangeais","rangeait","rangions","rangiez","rangeaient"],
    ["réaliser","to achieve,  to understand","réalisais","réalisais","réalisait","réalisions","réalisiez","réalisaient"],
    ["remercier","to thank","remerciais","remerciais","remerciait","remerciions","remerciiez","remerciaient"],
    ["rentrer","to go back in","rentrais","rentrais","rentrait","rentrions","rentriez","rentraient"],
    ["repousser","to postpone, to push away","repoussais","repoussais","repoussait","repoussions","repoussiez","repoussaient"],
    ["réserver","to book","réservais","réservais","réservait","réservions","réserviez","réservaient"],
    ["respecter","to respect","respectais","respectais","respectait","respections","respectiez","respectaient"],
    ["rester","to stay","restais","restais","restait","restions","restiez","restaient"],
    ["retourner","to go back","retournais","retournais","retournait","retournions","retourniez","retournaient"],
    ["simplifier","to simplify","simplifiais","simplifiais","simplifiait","simplifiions","simplifiiez","simplifiaient"],
    ["téléphoner","to call on the phone","téléphonais","téléphonais","téléphonait","téléphonions","téléphoniez","téléphonaient"],
    ["tomber","to fall","tombais","tombais","tombait","tombions","tombiez","tombaient"],
    ["tourner","to turn","tournais","tournais","tournait","tournions","tourniez","tournaient"],
    ["travailler","to work","travaillais","travaillais","travaillait","travaillions","travailliez","travaillaient"],
    ["traverser","to cross","traversais","traversais","traversait","traversions","traversiez","traversaient"],
    ["trouver","to find","trouvais","trouvais","trouvait","trouvions","trouviez","trouvaient"],
    ["vider","to empty","vidais","vidais","vidait","vidions","vidiez","vidaient"],
    ["voyager","to travel","voyageais","voyageais","voyageait","voyagions","voyagiez","voyageaient"],
    ["accomplir","to accomplish","accomplissais","accomplissais","accomplissait","accomplissions","accomplissiez","accomplissaient"],
    ["agir","to act","agissais","agissais","agissait","agissions","agissiez","agissaient"],
    ["avertir","to warn","avertissais","avertissais","avertissait","avertissions","avertissiez","avertissaient"],
    ["choisir","to choose","choisissais","choisissais","choisissait","choisissions","choisissiez","choisissaient"],
    ["finir","to finish","finissais","finissais","finissait","finissions","finissiez","finissaient"],
    ["grandir","to grow","grandissais","grandissais","grandissait","grandissions","grandissiez","grandissaient"],
    ["grossir","to get bigger","grossissais","grossissais","grossissait","grossissions","grossissiez","grossissaient"],
    ["guérir","to heal","guérissais","guérissais","guérissait","guérissions","guérissiez","guérissaient"],
    ["maigrir","to loose weight","maigrissais","maigrissais","maigrissait","maigrissions","maigrissiez","maigrissaient"],
    ["obéir","to obey","obéissais","obéissais","obéissait","obéissions","obéissiez","obéissaient"],
    ["réagir","to react","réagissais","réagissais","réagissait","réagissions","réagissiez","réagissaient"],
    ["réfléchir","to think, reflect","réfléchissais","réfléchissais","réfléchissait","réfléchissions","réfléchissiez","réfléchissaient"],
    ["refroidir","to cool down","refroidissais","refroidissais","refroidissait","refroidissions","refroidissiez","refroidissaient"],
    ["remplir","to fill","remplissais","remplissais","remplissait","remplissions","remplissiez","remplissaient"],
    ["réussir","to succeed","réussissais","réussissais","réussissait","réussissions","réussissiez","réussissaient"],
    ["rougir","to turn red, blush","rougissais","rougissais","rougissait","rougissions","rougissiez","rougissaient"],
    ["vieillir","to get older","vieillissais","vieillissais","vieillissait","vieillissions","vieillissiez","vieillissaient"],
    ["admettre","to admit","admettais","admettais","admettait","admettions","admettiez","admettaient"],
    ["aller","to go","allais","allais","allait","allions","alliez","allaient"],
    ["attendre","to wait","attendais","attendais","attendait","attendions","attendiez","attendaient"],
    ["avoir","to have","avais","avais","avait","avions","aviez","avaient"],
    ["boire","to drink","buvais","buvais","buvait","buvions","buviez","buvaient"],
    ["commettre","to commit","commettais","commettais","commettait","commettions","commettiez","commettaient"],
    ["comprendre","to understand","comprenais","comprenais","comprenait","comprenions","compreniez","comprenaient"],
    ["connaître","to know something","connaissais","connaissais","connaissait","connaissions","connaissiez","connaissaient"],
    ["croire","to believe","croyais","croyais","croyait","croyions","croyiez","croyaient"],
    ["défendre","to defend, forbid","défendais","défendais","défendait","défendions","défendiez","défendaient"],
    ["descendre","to go down","descendais","descendais","descendait","descendions","descendiez","descendaient"],
    ["devenir","to become","devenais","devenais","devenait","devenions","deveniez","devenaient"],
    ["devoir","to have to","devais","devais","devait","devions","deviez","devaient"],
    ["dormir","to sleep","dormais","dormais","dormait","dormions","dormiez","dormaient"],
    ["écrire","to write","écrivais","écrivais","écrivait","écrivions","écriviez","écrivaient"],
    ["entendre","to hear","entendais","entendais","entendait","entendions","entendiez","entendaient"],
    ["envoyer","to send","envoyais","envoyais","envoyait","envoyions","envoyiez","envoyaient"],
    ["espérer","to hope","espérais","espérais","espérait","espérions","espériez","espéraient"],
    ["être","to be","étais","étais","était","étions","étiez","étaient"],
    ["faire","to do","faisais","faisais","faisait","faisions","faisiez","faisaient"],
    ["mettre","to set, to put on","mettais","mettais","mettait","mettions","mettiez","mettaient"],
    ["mourir","to die","mourais","mourais","mourait","mourions","mouriez","mouraient"],
    ["naître","to be born","naissais","naissais","naissait","naissions","naissiez","naissaient"],
    ["partir","to leave","partais","partais","partait","partions","partiez","partaient"],
    ["perdre","to loose","perdais","perdais","perdait","perdions","perdiez","perdaient"],
    ["permettre","to allow","permettais","permettais","permettait","permettions","permettiez","permettaient"],
    ["pouvoir","to be able to","pouvais","pouvais","pouvait","pouvions","pouviez","pouvaient"],
    ["prendre","to take","prenais","prenais","prenait","prenions","preniez","prenaient"],
    ["promettre","to promise","promettais","promettais","promettait","promettions","promettiez","promettaient"],
    ["remettre","to postpone","remettais","remettais","remettait","remettions","remettiez","remettaient"],
    ["rendre","to give back","rendais","rendais","rendait","rendions","rendiez","rendaient"],
    ["répondre","to answer","répondais","répondais","répondait","répondions","répondiez","répondaient"],
    ["revenir","to come back","revenais","revenais","revenait","revenions","reveniez","revenaient"],
    ["rire","to laugh","riais","riais","riait","riions","riiez","riaient"],
    ["savoir","to know how to","savais","savais","savait","savions","saviez","savaient"],
    ["sortir","to go out","sortais","sortais","sortait","sortions","sortiez","sortaient"],
    ["sourire","to smile","souriais","souriais","souriait","souriions","souriiez","souriaient"],
    ["suivre","to follow","suivais","suivais","suivait","suivions","suiviez","suivaient"],
    ["vendre","to sell","vendais","vendais","vendait","vendions","vendiez","vendaient"],
    ["venir","to come","venais","venais","venait","venions","veniez","venaient"],
    ["vouloir","to want","voulais","voulais","voulait","voulions","vouliez","voulaient"],
    [" s'habiller","to get dressed","m'habillais","t'habillais","s'habillait","nous habillions","vous habilliez","s'habillaient"],
    ["s'aimer","to love each other","m'aimais","t'aimais","s'aimait","nous aimions","vous aimiez","s'aimaient"],
    ["s'amuser","to have fun","m'amusais","t'amusais","s'amusait","nous amusions","vous amusiez","s'amusaient"],
    ["s'appeler","to be named","m'appelais","t'appelais","s'appelait","nous appelions","vous appeliez","s'appelaient"],
    ["s'arrêter","to stop","m'arrêtais","t'arrêtais","s'arrêtait","nous arrêtions","vous arrêtiez","s'arrêtaient"],
    ["se brosser","to brush","me brossais","te brossais","se brossait","nous brossions","vous brossiez","se brossaient"],
    ["se confier","to confide","me confiais","te confiais","se confiait","nous confiions","vous confiiez","se confiaient"],
    ["se coucher","to go to bed","me couchais","te couchais","se couchait","nous couchions","vous couchiez","se couchaient"],
    ["se débrouiller","to manage","me débrouillais","te débrouillais","se débrouillait","nous débrouillions","vous débrouilliez","se débrouillaient"],
    ["se dépêcher","to hurry","me dépêchais","te dépêchais","se dépêchait","nous dépêchions","vous dépêchiez","se dépêchaient"],
    ["se détendre","to relax","me détendais","te détendais","se détendait","nous détendions","vous détendiez","se détendaient"],
    ["se disputer","to argue","me disputais","te disputais","se disputait","nous disputions","vous disputiez","se disputaient"],
    ["se fâcher","to get angry","me fâchais","te fâchais","se fâchait","nous fâchions","vous fâchiez","se fâchaient"],
    ["se fiancer","to get engaged","me fiançais","te fiançais","se fiançait","nous fiancions","vous fianciez","se fiançaient"],
    ["se laver ","to wash","me lavais","te lavais","se lavait","nous lavions","vous laviez","se lavaient"],
    ["se lever","to get up","me levais","te levais","se levait","nous levions","vous leviez","se levaient"],
    ["se marier","to get married","me mariais","te mariais","se mariait","nous mariions","vous mariiez","se mariaient"],
    ["se méfier","to distrust","me méfiais","te méfiais","se méfiait","nous méfiions","vous méfiiez","se méfiaient"],
    ["se passer","to do without","me passais","te passais","se passait","nous passions","vous passiez","se passaient"],
    ["se peigner","to comb","me peignais","te peignais","se peignait","nous peignions","vous peigniez","se peignaient"],
    ["se préparer","to get ready","me préparais","te préparais","se préparait","nous préparions","vous prépariez","se préparaient"],
    ["se rappeler","to recall","me rappelais","te rappelais","se rappelait","nous rappelions","vous rappeliez","se rappelaient"],
    ["se raser","to shave","me rasais","te rasais","se rasait","nous rasions","vous rasiez","se rasaient"],
    ["se reposer","to relax","me reposais","te reposais","se reposait","nous reposions","vous reposiez","se reposaient"],
    ["se réveiller","to wake up","me réveillais","te réveillais","se réveillait","nous réveillions","vous réveilliez","se réveillaient"],
    ["se sentir","to feel","me sentais","te sentais","se sentait","nous sentions","vous sentiez","se sentaient"],
    ["se souvenir","to remember","me souvenais","te souvenais","se souvenait","nous souvenions","vous souveniez","se souvenaient"],
    ["s'embrasser","to kiss ","m'embrassais","t'embrassais","s'embrassait","nous embrassions","vous embrassiez","s'embrassaient"],
    ["s'entendre","to get along","m'entendais","t'entendais","s'entendait","nous entendions","vous entendiez","s'entendaient"],
    ["s'habituer","to get used to","m'habituais","t'habituais","s'habituait","nous habituions","vous habituiez","s'habituaient"],
    ["s'intéresser","to be interested in","m'intéressais","t'intéressais","s'intéressait","nous intéressions","vous intéressiez","s'intéressaient"],
    ["s'occuper","to take care of","m'occupais","t'occupais","s'occupait","nous occupions","vous occupiez","s'occupaient"]
];

var passéComposé = [
    ["passé composé","empty","je","tu","il ","elle","nous","vous","ils","elles"],
    ["abandonner","to abandon","ai abandonné","as abandonné","a abandonné","a abandonné","avons abandonné","avez abandonné","ont abandonné","ont abandonné"],
    ["acheter","to buy","ai acheté","as acheté","a acheté","a acheté","avons acheté","avez acheté","ont acheté","ont acheté"],
    ["admirer","to admire","ai admiré","as admiré","a admiré","a admiré","avons admiré","avez admiré","ont admiré","ont admiré"],
    ["adorer","to adore","ai adoré","as adoré","a adoré","a adoré","avons adoré","avez adoré","ont adoré","ont adoré"],
    ["aider","to help","ai aidé","as aidé","a aidé","a aidé","avons aidé","avez aidé","ont aidé","ont aidé"],
    ["aimer","to like, love","ai aimé","as aimé","a aimé","a aimé","avons aimé","avez aimé","ont aimé","ont aimé"],
    ["ajouter","to add","ai ajouté","as ajouté","a ajouté","a ajouté","avons ajouté","avez ajouté","ont ajouté","ont ajouté"],
    ["appeler","to call","ai appelé","as appelé","a appelé","a appelé","avons appelé","avez appelé","ont appelé","ont appelé"],
    ["apporter","to bring","ai apporté","as apporté","a apporté","a apporté","avons apporté","avez apporté","ont apporté","ont apporté"],
    ["arriver","to arrive","suis arrivé","es arrivé","est arrivé","est arrivée","sommes arrivés","êtes arrivés","sont arrivés","sont arrivées"],
    ["attraper","to catch","ai attrapé","as attrapé","a attrapé","a attrapé","avons attrapé","avez attrapé","ont attrapé","ont attrapé"],
    ["augmenter","to increase","ai augmenté","as augmenté","a augmenté","a augmenté","avons augmenté","avez augmenté","ont augmenté","ont augmenté"],
    ["bouger","to move","ai bougé","as bougé","a bougé","a bougé","avons bougé","avez bougé","ont bougé","ont bougé"],
    ["camper","to camp","ai campé","as campé","a campé","a campé","avons campé","avez campé","ont campé","ont campé"],
    ["changer","to change","ai changé","as changé","a changé","a changé","avons changé","avez changé","ont changé","ont changé"],
    ["chanter","to sing","ai chanté","as chanté","a chanté","a chanté","avons chanté","avez chanté","ont chanté","ont chanté"],
    ["chercher","to look for","ai cherché","as cherché","a cherché","a cherché","avons cherché","avez cherché","ont cherché","ont cherché"],
    ["commander","to order","ai commandé","as commandé","a commandé","a commandé","avons commandé","avez commandé","ont commandé","ont commandé"],
    ["compter","to count","ai compté","as compté","a compté","a compté","avons compté","avez compté","ont compté","ont compté"],
    ["consulter","to consult","ai consulté","as consulté","a consulté","a consulté","avons consulté","avez consulté","ont consulté","ont consulté"],
    ["continuer","to continue","ai continué","as continué","a continué","a continué","avons continué","avez continué","ont continué","ont continué"],
    ["couper","to cut","ai coupé","as coupé","a coupé","a coupé","avons coupé","avez coupé","ont coupé","ont coupé"],
    ["créer","to create","ai créé","as créé","a créé","a créé","avons créé","avez créé","ont créé","ont créé"],
    ["danser","to dance","ai dansé","as dansé","a dansé","a dansé","avons dansé","avez dansé","ont dansé","ont dansé"],
    ["décider","to decide","ai décidé","as décidé","a décidé","a décidé","avons décidé","avez décidé","ont décidé","ont décidé"],
    ["détester","to hate","ai détesté","as détesté","a détesté","a détesté","avons détesté","avez détesté","ont détesté","ont détesté"],
    ["diminuer","to decrease","ai diminué","as diminué","a diminué","a diminué","avons diminué","avez diminué","ont diminué","ont diminué"],
    ["dîner","to dine","ai dîné","as dîné","a dîné","a dîné","avons dîné","avez dîné","ont dîné","ont dîné"],
    ["donner","to give","ai donné","as donné","a donné","a donné","avons donné","avez donné","ont donné","ont donné"],
    ["échanger","to exchange","ai échangé","as échangé","a échangé","a échangé","avons échangé","avez échangé","ont échangé","ont échangé"],
    ["écouter","to listen","ai écouté","as écouté","a écouté","a écouté","avons écouté","avez écouté","ont écouté","ont écouté"],
    ["embaucher","to hire","ai embauché","as embauché","a embauché","a embauché","avons embauché","avez embauché","ont embauché","ont embauché"],
    ["embrasser","to kiss","ai embrassé","as embrassé","a embrassé","a embrassé","avons embrassé","avez embrassé","ont embrassé","ont embrassé"],
    ["emmener","to take someone","ai emmené","as emmené","a emmené","a emmené","avons emmené","avez emmené","ont emmené","ont emmené"],
    ["emprunter","to borrow","ai emprunté","as emprunté","a emprunté","a emprunté","avons emprunté","avez emprunté","ont emprunté","ont emprunté"],
    ["enseigner","to teach","ai enseigné","as enseigné","a enseigné","a enseigné","avons enseigné","avez enseigné","ont enseigné","ont enseigné"],
    ["entrer","to enter","suis entré","es entré","est entré","est entrée","sommes entrés","êtes entrés","sont entrés","sont entrées"],
    ["essayer","to try","ai essayé","as essayé","a essayé","a essayé","avons essayé","avez essayé","ont essayé","ont essayé"],
    ["étudier","to study","ai étudié","as étudié","a étudié","a étudié","avons étudié","avez étudié","ont étudié","ont étudié"],
    ["éviter","to avoid","ai évité","as évité","a évité","a évité","avons évité","avez évité","ont évité","ont évité"],
    ["exiger","to demand","ai exigé","as exigé","a exigé","a exigé","avons exigé","avez exigé","ont exigé","ont exigé"],
    ["expliquer","to explain","ai expliqué","as expliqué","a expliqué","a expliqué","avons expliqué","avez expliqué","ont expliqué","ont expliqué"],
    ["fermer","to close","ai fermé","as fermé","a fermé","a fermé","avons fermé","avez fermé","ont fermé","ont fermé"],
    ["garder","to keep","ai gardé","as gardé","a gardé","a gardé","avons gardé","avez gardé","ont gardé","ont gardé"],
    ["habiter","to live","ai habité","as habité","a habité","a habité","avons habité","avez habité","ont habité","ont habité"],
    ["indiquer","to indicate","ai indiqué","as indiqué","a indiqué","a indiqué","avons indiqué","avez indiqué","ont indiqué","ont indiqué"],
    ["inviter","to invite","ai invité","as invité","a invité","a invité","avons invité","avez invité","ont invité","ont invité"],
    ["jouer","to play","ai joué","as joué","a joué","a joué","avons joué","avez joué","ont joué","ont joué"],
    ["laisser","to leave, to let","ai laissé","as laissé","a laissé","a laissé","avons laissé","avez laissé","ont laissé","ont laissé"],
    ["laver","to wash","ai lavé","as lavé","a lavé","a lavé","avons lavé","avez lavé","ont lavé","ont lavé"],
    ["louer","to rent","ai loué","as loué","a loué","a loué","avons loué","avez loué","ont loué","ont loué"],
    ["manger","to eat","ai mangé","as mangé","a mangé","a mangé","avons mangé","avez mangé","ont mangé","ont mangé"],
    ["marcher","to walk","ai marché","as marché","a marché","a marché","avons marché","avez marché","ont marché","ont marché"],
    ["monter","to go up","suis monté","es monté","est monté","est montée","sommes montés","êtes montés","sont montés","sont montées"],
    ["nager","to swim","ai nagé","as nagé","a nagé","a nagé","avons nagé","avez nagé","ont nagé","ont nagé"],
    ["naviguer","to navigate","ai navigué","as navigué","a navigué","a navigué","avons navigué","avez navigué","ont navigué","ont navigué"],
    ["nettoyer","to clean","ai nettoyé","as nettoyé","a nettoyé","a nettoyé","avons nettoyé","avez nettoyé","ont nettoyé","ont nettoyé"],
    ["organiser","to organise","ai organisé","as organisé","a organisé","a organisé","avons organisé","avez organisé","ont organisé","ont organisé"],
    ["oublier","to forget","ai oublié","as oublié","a oublié","a oublié","avons oublié","avez oublié","ont oublié","ont oublié"],
    ["parler","to speak","ai parlé","as parlé","a parlé","a parlé","avons parlé","avez parlé","ont parlé","ont parlé"],
    ["partager","to share","ai partagé","as partagé","a partagé","a partagé","avons partagé","avez partagé","ont partagé","ont partagé"],
    ["passer","to pass, spend time","ai passé","as passé","a passé","a passé","avons passé","avez passé","ont passé","ont passé"],
    ["penser","to think","ai pensé","as pensé","a pensé","a pensé","avons pensé","avez pensé","ont pensé","ont pensé"],
    ["posséder","to own","ai possédé","as possédé","a possédé","a possédé","avons possédé","avez possédé","ont possédé","ont possédé"],
    ["préférer","to prefer","ai préféré","as préféré","a préféré","a préféré","avons préféré","avez préféré","ont préféré","ont préféré"],
    ["préparer","to prepare","ai préparé","as préparé","a préparé","a préparé","avons préparé","avez préparé","ont préparé","ont préparé"],
    ["profiter","to enjoy, to profit","ai profité","as profité","a profité","a profité","avons profité","avez profité","ont profité","ont profité"],
    ["proposer","to propose","ai proposé","as proposé","a proposé","a proposé","avons proposé","avez proposé","ont proposé","ont proposé"],
    ["quitter","to leave someone or something","ai quitté","as quitté","a quitté","a quitté","avons quitté","avez quitté","ont quitté","ont quitté"],
    ["ranger","to put away, to clean up","ai rangé","as rangé","a rangé","a rangé","avons rangé","avez rangé","ont rangé","ont rangé"],
    ["réaliser","to achieve,  to understand","ai réalisé","as réalisé","a réalisé","a réalisé","avons réalisé","avez réalisé","ont réalisé","ont réalisé"],
    ["remercier","to thank","ai remercié","as remercié","a remercié","a remercié","avons remercié","avez remercié","ont remercié","ont remercié"],
    ["rentrer","to go back in","suis rentré","es rentré","est rentré","est rentrée","sommes rentrés","êtes rentrés","sont rentrés","sont rentrées"],
    ["repousser","to postpone, to push away","ai repoussé","as repoussé","a repoussé","a repoussé","avons repoussé","avez repoussé","ont repoussé","ont repoussé"],
    ["réserver","to book","ai réservé","as réservé","a réservé","a réservé","avons réservé","avez réservé","ont réservé","ont réservé"],
    ["respecter","to respect","ai respecté","as respecté","a respecté","a respecté","avons respecté","avez respecté","ont respecté","ont respecté"],
    ["rester","to stay","suis resté","es resté","est resté","est restée","sommes restés","êtes restés","sont restés","sont restées"],
    ["retourner","to go back","suis retourné","es retourné","est retourné","est retournée","sommes retournés","êtes retournés","sont retournés","sont retournées"],
    ["simplifier","to simplify","ai simplifié","as simplifié","a simplifié","a simplifié","avons simplifié","avez simplifié","ont simplifié","ont simplifié"],
    ["téléphoner","to call on the phone","ai téléphoné","as téléphoné","a téléphoné","a téléphoné","avons téléphoné","avez téléphoné","ont téléphoné","ont téléphoné"],
    ["tomber","to fall","suis tombé","es tombé","est tombé","est tombée","sommes tombés","êtes tombés","sont tombés","sont tombées"],
    ["tourner","to turn","ai tourné","as tourné","a tourné","a tourné","avons tourné","avez tourné","ont tourné","ont tourné"],
    ["travailler","to work","ai travaillé","as travaillé","a travaillé","a travaillé","avons travaillé","avez travaillé","ont travaillé","ont travaillé"],
    ["traverser","to cross","ai traversé","as traversé","a traversé","a traversé","avons traversé","avez traversé","ont traversé","ont traversé"],
    ["trouver","to find","ai trouvé","as trouvé","a trouvé","a trouvé","avons trouvé","avez trouvé","ont trouvé","ont trouvé"],
    ["vider","to empty","ai vidé","as vidé","a vidé","a vidé","avons vidé","avez vidé","ont vidé","ont vidé"],
    ["voyager","to travel","ai voyagé","as voyagé","a voyagé","a voyagé","avons voyagé","avez voyagé","ont voyagé","ont voyagé"],
    ["accomplir","to accomplish","ai accompli","as accompli","a accompli","a accompli","avons accompli","avez accompli","ont accompli","ont accompli"],
    ["agir","to act","ai agi","as agi","a agi","a agi","avons agi","avez agi","ont agi","ont agi"],
    ["avertir","to warn","ai averti","as averti","a averti","a averti","avons averti","avez averti","ont averti","ont averti"],
    ["choisir","to choose","ai choisi","as choisi","a choisi","a choisi","avons choisi","avez choisi","ont choisi","ont choisi"],
    ["finir","to finish","ai fini","as fini","a fini","a fini","avons fini","avez fini","ont fini","ont fini"],
    ["grandir","to grow","ai grandi","as grandi","a grandi","a grandi","avons grandi","avez grandi","ont grandi","ont grandi"],
    ["grossir","to get bigger","ai grossi","as grossi","a grossi","a grossi","avons grossi","avez grossi","ont grossi","ont grossi"],
    ["guérir","to heal","ai guéri","as guéri","a guéri","a guéri","avons guéri","avez guéri","ont guéri","ont guéri"],
    ["maigrir","to loose weight","ai maigri","as maigri","a maigri","a maigri","avons maigri","avez maigri","ont maigri","ont maigri"],
    ["obéir","to obey","ai obéi","as obéi","a obéi","a obéi","avons obéi","avez obéi","ont obéi","ont obéi"],
    ["réagir","to react","ai réagi","as réagi","a réagi","a réagi","avons réagi","avez réagi","ont réagi","ont réagi"],
    ["réfléchir","to think, reflect","ai réfléchi","as réfléchi","a réfléchi","a réfléchi","avons réfléchi","avez réfléchi","ont réfléchi","ont réfléchi"],
    ["refroidir","to cool down","ai refroidi","as refroidi","a refroidi","a refroidi","avons refroidi","avez refroidi","ont refroidi","ont refroidi"],
    ["remplir","to fill","ai rempli","as rempli","a rempli","a rempli","avons rempli","avez rempli","ont rempli","ont rempli"],
    ["réussir","to succeed","ai réussi","as réussi","a réussi","a réussi","avons réussi","avez réussi","ont réussi","ont réussi"],
    ["rougir","to turn red, blush","ai rougi","as rougi","a rougi","a rougi","avons rougi","avez rougi","ont rougi","ont rougi"],
    ["vieillir","to get older","ai vieilli","as vieilli","a vieilli","a vieilli","avons vieilli","avez vieilli","ont vieilli","ont vieilli"],
    ["admettre","to admit","ai admis","as admis","a admis","a admis","avons admis","avez admis","ont admis","ont admis"],
    ["aller","to go","suis allé","es allé","est allé","est allée","sommes allés","êtes allés","sont allés","sont allées"],
    ["attendre","to wait","ai attendu","as attendu","a attendu","a attendu","avons attendu","avez attendu","ont attendu","ont attendu"],
    ["avoir","to have","ai eu","as eu","a eu","a eu","avons eu","avez eu","ont eu","ont eu"],
    ["boire","to drink","ai bu","as bu","a bu","a bu","avons bu","avez bu","ont bu","ont bu"],
    ["commettre","to commit","ai commis","as commis","a commis","a commis","avons commis","avez commis","ont commis","ont commis"],
    ["comprendre","to understand","ai compris","as compris","a compris","a compris","avons compris","avez compris","ont compris","ont compris"],
    ["connaître","to know something","ai connu","as connu","a connu","a connu","avons connu","avez connu","ont connu","ont connu"],
    ["croire","to believe","ai cru","as cru","a cru","a cru","avons cru","avez cru","ont cru","ont cru"],
    ["défendre","to defend, forbid","ai défendu","as défendu","a défendu","a défendu","avons défendu","avez défendu","ont défendu","ont défendu"],
    ["descendre","to go down","suis descendu","es descendu","est descendu","est descendue","sommes descendus","êtes descendus","sont descendus","sont descendues"],
    ["devenir","to become","suis devenu","es devenu","est devenu","est devenue","sommes devenus","êtes devenus","sont devenus","sont devenues"],
    ["devoir","to have to","ai dû","as dû","a dû","a dû","avons dû","avez dû","ont dû","ont dû"],
    ["dormir","to sleep","ai dormi","as dormi","a dormi","a dormi","avons dormi","avez dormi","ont dormi","ont dormi"],
    ["écrire","to write","ai écrit","as écrit","a écrit","a écrit","avons écrit","avez écrit","ont écrit","ont écrit"],
    ["entendre","to hear","ai entendu","as entendu","a entendu","a entendu","avons entendu","avez entendu","ont entendu","ont entendu"],
    ["envoyer","to send","ai envoyé","as envoyé","a envoyé","a envoyé","avons envoyé","avez envoyé","ont envoyé","ont envoyé"],
    ["espérer","to hope","ai espéré","as espéré","a espéré","a espéré","avons espéré","avez espéré","ont espéré","ont espéré"],
    ["être","to be","ai été","as été","a été","a été","avons été","avez été","ont été","ont été"],
    ["faire","to do","ai fait","as fait","a fait","a fait","avons fait","avez fait","ont fait","ont fait"],
    ["mettre","to set, to put on","ai mis","as mis","a mis","a mis","avons mis","avez mis","ont mis","ont mis"],
    ["mourir","to die","suis mort","es mort","est mort","est morte","sommes morts","êtes morts","sont morts","sont mortes"],
    ["naître","to be born","suis né","es né","est né","est née","sommes nés","êtes nés","sont nés","sont nées"],
    ["partir","to leave","suis parti","es parti","est parti","est partie","sommes partis","êtes partis","sont partis","sont parties"],
    ["perdre","to loose","ai perdu","as perdu","a perdu","a perdu","avons perdu","avez perdu","ont perdu","ont perdu"],
    ["permettre","to allow","ai permis","as permis","a permis","a permis","avons permis","avez permis","ont permis","ont permis"],
    ["pouvoir","to be able to","ai pu","as pu","a pu","a pu","avons pu","avez pu","ont pu","ont pu"],
    ["prendre","to take","ai pris","as pris","a pris","a pris","avons pris","avez pris","ont pris","ont pris"],
    ["promettre","to promise","ai permis","as permis","a permis","a permis","avons permis","avez permis","ont permis","ont permis"],
    ["remettre","to postpone","ai remis","as remis","a remis","a remis","avons remis","avez remis","ont remis","ont remis"],
    ["rendre","to give back","ai rendu","as rendu","a rendu","a rendu","avons rendu","avez rendu","ont rendu","ont rendu"],
    ["répondre","to answer","ai répondu","as répondu","a répondu","a répondu","avons répondu","avez répondu","ont répondu","ont répondu"],
    ["revenir","to come back","suis revenu","es revenu","est revenu","est revenue","sommes revenus","êtes revenus","sont revenus","sont revenues"],
    ["rire","to laugh","ai ri","as ri","a ri","a ri","avons ri","avez ri","ont ri","ont ri"],
    ["savoir","to know how to","ai su","as su","a su","a su","avons su","avez su","ont su","ont su"],
    ["sortir","to go out","suis sorti","es sorti","est sorti","est sortie","sommes sortis","êtes sortis","sont sortis","sont sorties"],
    ["sourire","to smile","ai souri","as souri","a souri","a souri","avons souri","avez souri","ont souri","ont souri"],
    ["suivre","to follow","ai suivi","as suivi","a suivi","a suivi","avons suivi","avez suivi","ont suivi","ont suivi"],
    ["vendre","to sell","ai vendu","as vendu","a vendu","a vendu","avons vendu","avez vendu","ont vendu","ont vendu"],
    ["venir","to come","suis venu","es venu","est venu","est venue","sommes venus","êtes venus","sont venus","sont venues"],
    ["vouloir","to want","ai voulu","as voulu","a voulu","a voulu","avons voulu","avez voulu","ont voulu","ont voulu"],
    [" s'habiller","to get dressed","me suis habillé","t'es habillé","s'est habillé","s'est habillée","nous sommes habillés","vous êtes habillés","se sont habillés","se sont habillées"],
    ["s'aimer","to love each other","me suis aimé","t'es aimé","s'est aimé","s'est aimée","nous sommes aimés","vous êtes aimés","se sont aimés","se sont aimées"],
    ["s'amuser","to have fun","me suis amusé","t'es amusé","s'est amusé","s'est amusée","nous sommes amusés","vous êtes amusés","se sont amusés","se sont amusées"],
    ["s'appeler","to be named","me suis appelé","t'es appelé","s'est appelé","s'est appelée","nous sommes appelés","vous êtes appelés","se sont appelés","se sont appelées"],
    ["s'arrêter","to stop","me suis arrêté","t'es arrêté","s'est arrêté","s'est arrêtée","nous sommes arrêtés","vous êtes arrêtés","se sont arrêtés","se sont arrêtées"],
    ["se brosser","to brush","me suis brossé","t'es brossé","s'est brossé","s'est brossée","nous sommes brossés","vous êtes brossés","se sont brossés","se sont brossées"],
    ["se confier","to confide","me suis confié","t'es confié","s'est confié","s'est confiée","nous sommes confiés","vous êtes confiés","se sont confiés","se sont confiées"],
    ["se coucher","to go to bed","me suis couché","t'es couché","s'est couché","s'est couchée","nous sommes couchés","vous êtes couchés","se sont couchés","se sont couchées"],
    ["se débrouiller","to manage","me suis débrouillé","t'es débrouillé","s'est débrouillé","s'est débrouillée","nous sommes débrouillés","vous êtes débrouillés","se sont débrouillés","se sont débrouillées"],
    ["se dépêcher","to hurry","me suis dépêché","t'es dépêché","s'est dépêché","s'est dépêchée","nous sommes dépêchés","vous êtes dépêchés","se sont dépêchés","se sont dépêchées"],
    ["se détendre","to relax","me suis détendu","t'es détendu","s'est détendu","s'est détendue","nous sommes détendus","vous êtes détendus","se sont détendus","se sont détendues"],
    ["se disputer","to argue","me suis disputé","t'es disputé","s'est disputé","s'est disputée","nous sommes disputés","vous êtes disputés","se sont disputés","se sont disputées"],
    ["se fâcher","to get angry","me suis fâché","t'es fâché","s'est fâché","s'est fâchée","nous sommes fâchés","vous êtes fâchés","se sont fâchés","se sont fâchées"],
    ["se fiancer","to get engaged","me suis fiancé","t'es fiancé","s'est fiancé","s'est fiancée","nous sommes fiancés","vous êtes fiancés","se sont fiancés","se sont fiancées"],
    ["se laver ","to wash","me suis lavé","t'es lavé","s'est lavé","s'est lavée","nous sommes lavés","vous êtes lavés","se sont lavés","se sont lavées"],
    ["se lever","to get up","me suis levé","t'es levé","s'est levé","s'est levée","nous sommes levés","vous êtes levés","se sont levés","se sont levées"],
    ["se marier","to get married","me suis marié","t'es marié","s'est marié","s'est mariée","nous sommes mariés","vous êtes mariés","se sont mariés","se sont mariées"],
    ["se méfier","to distrust","me suis méfié","t'es méfié","s'est méfié","s'est méfiée","nous sommes méfiés","vous êtes méfiés","se sont méfiés","se sont méfiées"],
    ["se passer","to do without","me suis passé","t'es passé","s'est passé","s'est passée","nous sommes passés","vous êtes passés","se sont passés","se sont passées"],
    ["se peigner","to comb","me suis peigné","t'es peigné","s'est peigné","s'est peignée","nous sommes peignés","vous êtes peignés","se sont peignés","se sont peignées"],
    ["se préparer","to get ready","me suis préparé","t'es préparé","s'est préparé","s'est préparée","nous sommes préparés","vous êtes préparés","se sont préparés","se sont préparées"],
    ["se rappeler","to recall","me suis rappelé","t'es rappelé","s'est rappelé","s'est rappelée","nous sommes rappelés","vous êtes rappelés","se sont rappelés","se sont rappelées"],
    ["se raser","to shave","me suis rasé","t'es rasé","s'est rasé","s'est rasée","nous sommes rasés","vous êtes rasés","se sont rasés","se sont rasées"],
    ["se reposer","to relax","me suis reposé","t'es reposé","s'est reposé","s'est reposée","nous sommes reposés","vous êtes reposés","se sont reposés","se sont reposées"],
    ["se réveiller","to wake up","me suis réveillé","t'es réveillé","s'est réveillé","s'est réveillée","nous sommes réveillés","vous êtes réveillés","se sont réveillés","se sont réveillées"],
    ["se sentir","to feel","me suis senti","t'es senti","s'est senti","s'est sentie","nous sommes sentis","vous êtes sentis","se sont sentis","se sont senties"],
    ["se souvenir","to remember","me suis souvenu","t'es souvenu","s'est souvenu","s'est souvenue","nous sommes souvenus","vous êtes souvenus","se sont souvenus","se sont souvenues"],
    ["s'embrasser","to kiss ","me suis embrassé","t'es embrassé","s'est embrassé","s'est embrassée","nous sommes embrassés","vous êtes embrassés","se sont embrassés","se sont embrassées"],
    ["s'entendre","to get along","me suis entendu","t'es entendu","s'est entendu","s'est entendue","nous sommes entendus","vous êtes entendus","se sont entendus","se sont entendues"],
    ["s'habituer","to get used to","me suis habitué","t'es habitué","s'est habitué","s'est habituée","nous sommes habitués","vous êtes habitués","se sont habitués","se sont habituées"],
    ["s'intéresser","to be interested in","me suis intéressé","t'es intéressé","s'est intéressé","s'est intéressée","nous sommes intéressés","vous êtes intéressés","se sont intéressés","se sont intéressées"],
    ["s'occuper","to take care of","me suis occupé","t'es occupé","s'est occupé","s'est occupée","nous sommes occupés","vous êtes occupés","se sont occupés","se sont occupées"]
];

var imperatif = [
    ["impératif","empty","(tu)","(nous)","(vous)"],
    ["abandonner ","to abandon","abandonne","abandonnons","abandonnez"],
    ["acheter ","to buy","achète","achetons","achetez"],
    ["admirer ","to admire","admire","admirons","admirez"],
    ["adorer","to adore","adore","adorons","adorez"],
    ["aider ","to help","aide","aidons","aidez"],
    ["aimer ","to like, love","aime","aimons","aimez"],
    ["ajouter ","to add","ajoute","ajoutons","ajoutez"],
    ["appeler ","to call","appelle","appelons","appelez"],
    ["apporter","to bring","apporte","apportons","apportez"],
    ["arriver","to arrive","arrive","arrivons","arrivez"],
    ["attraper","to catch","attrape","attrapons","attrapez"],
    ["augmenter","to increase","augmente","augmentons","augmentez"],
    ["bouger","to move","bouge","bougeons","bougez"],
    ["camper","to camp","campe","campons","campez"],
    ["changer","to change","change","changeons","changez"],
    ["chanter","to sing","chante","chantons","chantez"],
    ["chercher","to look for","cherche","cherchons","cherchez"],
    ["commander","to order","commande","commandons","commandez"],
    ["compter","to count","compte","comptons","comptez"],
    ["consulter","to consult","consulte","consultons","consultez"],
    ["continuer","to continue","continue","continuons","continuez"],
    ["couper","to cut","coupe","coupons","coupez"],
    ["créer","to create","crée","créons","créez"],
    ["danser","to dance","danse","dansons","dansez"],
    ["décider","to decide","décide","décidons","décidez"],
    ["détester","to hate","déteste","détestons","détestez"],
    ["diminuer","to decrease","diminue","diminuons","diminuez"],
    ["dîner","to dine","dîne","dînons","dînez"],
    ["donner","to give","donne","donnons","donnez"],
    ["échanger","to exchange","échange","échangeons","échangez"],
    ["écouter","to listen","écoute","écoutons","écoutez"],
    ["embaucher","to hire","embauche","embauchons","embauchez"],
    ["embrasser","to kiss","embrasse","embrassons","embrassez"],
    ["emmener","to take someone","emmène","emmenons","emmenez"],
    ["emprunter","to borrow","emprunte","empruntons","empruntez"],
    ["enseigner","to teach","enseigne","enseignons","enseignez"],
    ["entrer","to enter","entre","entrons","entrez"],
    ["essayer","to try","essaie","essayons","essayez"],
    ["étudier","to study","étudie","étudions","étudiez"],
    ["éviter","to avoid","évite","évitons","évitez"],
    ["exiger","to demand","exige","exigeons","exigez"],
    ["expliquer","to explain","explique","expliquons","expliquez"],
    ["fermer","to close","ferme","fermons","fermez"],
    ["garder","to keep","garde","gardons","gardez"],
    ["habiter","to live","habite","habitons","habitez"],
    ["indiquer","to indicate","indique","indiquons","indiquez"],
    ["inviter","to invite","invite","invitons","invitez"],
    ["jouer","to play","joue","jouons","jouez"],
    ["laisser","to leave, to let","laisse","laissons","laissez"],
    ["laver","to wash","lave","lavons","lavez"],
    ["louer","to rent","loue","louons","louez"],
    ["manger","to eat","mange","mangeons","mangez"],
    ["marcher","to walk","marche","marchons","marchez"],
    ["monter","to go up","monte","montons","montez"],
    ["nager","to swim","nage","nageons","nagez"],
    ["naviguer","to navigate","navigue","naviguons","naviguez"],
    ["nettoyer","to clean","nettoie","nettoyons","nettoyez"],
    ["organiser","to organise","organise","organisons","organisez"],
    ["oublier","to forget","oublie","oublions","oubliez"],
    ["parler","to speak","parle","parlons","parlez"],
    ["partager","to share","partage","partageons","partagez"],
    ["passer","to pass, spend time","passe","passons","passez"],
    ["penser","to think","pense","pensons","pensez"],
    ["posséder","to own","possède","possédons","possédez"],
    ["préférer","to prefer","préfère","préférons","préférez"],
    ["préparer","to prepare","prépare","préparons","préparez"],
    ["profiter","to enjoy, to profit","profite","profitons","profitez"],
    ["proposer","to propose","propose","proposons","proposez"],
    ["quitter","to leave someone or something","quitte","quittons","quittez"],
    ["ranger","to put away, to clean up","range","rangeons","rangez"],
    ["réaliser","to achieve,  to understand","réalise","réalisons","réalisez"],
    ["remercier","to thank","remercie","remercions","remerciez"],
    ["rentrer","to go back in","rentre","rentrons","rentrez"],
    ["repousser","to postpone, to push away","repousse","repoussons","repoussez"],
    ["réserver","to book","réserve","réservons","réservez"],
    ["respecter","to respect","respecte","respectons","respectez"],
    ["rester","to stay","reste","restons","restez"],
    ["retourner","to go back","retourne","retournons","retournez"],
    ["simplifier","to simplify","simplifie","simplifions","simplifiez"],
    ["téléphoner","to call on the phone","téléphone","téléphonons","téléphonez"],
    ["tomber","to fall","tombe","tombons","tombez"],
    ["tourner","to turn","tourne","tournons","tournez"],
    ["travailler","to work","travaille","travaillons","travaillez"],
    ["traverser","to cross","traverse","traversons","traversez"],
    ["trouver","to find","trouve","trouvons","trouvez"],
    ["vider","to empty","vide","vidons","videz"],
    ["voyager","to travel","voyage","voyageons","voyagez"],
    ["accomplir","to accomplish","accomplis","accomplissons","accomplissez"],
    ["agir","to act","agis","agissons","agissez"],
    ["avertir","to warn","avertis","avertissons","avertissez"],
    ["choisir","to choose","choisis","choisissons","choisissez"],
    ["finir","to finish","finis","finissons","finissez"],
    ["grandir","to grow","grandis","grandissons","grandissez"],
    ["grossir","to get bigger","grossis","grossissons","grossissez"],
    ["guérir","to heal","guéris","guérissons","guérissez"],
    ["maigrir","to loose weight","maigris","maigrissons","maigrissez"],
    ["obéir","to obey","obéis","obéissons","obéissez"],
    ["réagir","to react","réagis","réagissons","réagissez"],
    ["réfléchir","to think, reflect","réfléchis","réfléchissons","réfléchissez"],
    ["refroidir","to cool down","refroidis","refroidissons","refroidissez"],
    ["remplir","to fill","remplis","remplissons","remplissez"],
    ["réussir","to succeed","réussis","réussissons","réussissez"],
    ["rougir","to turn red, blush","rougis","rougissons","rougissez"],
    ["vieillir","to get older","vieillis","vieillissons","vieillissez"],
    ["admettre","to admit","admets","admettons","admettez"],
    ["aller","to go","va","allons","allez"],
    ["attendre","to wait","attends","attendons","attendez"],
    ["avoir","to have","aie","ayons","ayez"],
    ["boire","to drink","bois","buvons","buvez"],
    ["commettre","to commit","commets","commettons","commettez"],
    ["comprendre","to understand","comprends","comprenons","comprenez"],
    ["connaître","to know something","connais","connaissons","connaissez"],
    ["croire","to believe","crois","croyons","croyez"],
    ["défendre","to defend, forbid","défends","défendons","défendez"],
    ["descendre","to go down","descends","descendons","descendez"],
    ["devenir","to become","deviens","devenons","devenez"],
    ["dormir","to sleep","dors","dormons","dormez"],
    ["écrire","to write","écris","écrivons","écrivez"],
    ["entendre","to hear","entends","entendons","entendez"],
    ["envoyer","to send","envoie","envoyons","envoyez"],
    ["espérer","to hope","espère","espérons","espérez"],
    ["être","to be","sois","soyons","soyez"],
    ["faire","to do","fais","faisons","faites"],
    ["mettre","to set, to put on","mets","mettons","mettez"],
    ["mourir","to die","meurs","mourons","mourez"],
    ["partir","to leave","pars","partons","partez"],
    ["perdre","to loose","perds","perdons","perdez"],
    ["permettre","to allow","permets","permettons","permettez"],
    ["prendre","to take","prends","prenons","prenez"],
    ["promettre","to promise","promets","promettons","promettez"],
    ["remettre","to postpone","remets","remettons","remettez"],
    ["rendre","to give back","rends","rendons","rendez"],
    ["répondre","to answer","réponds","répondons","répondez"],
    ["revenir","to come back","reviens","revenons","revenez"],
    ["rire","to laugh","ris","rions","riez"],
    ["savoir","to know how to","sache","sachons","sachez"],
    ["sortir","to go out","sors","sortons","sortez"],
    ["sourire","to smile","souris","sourions","souriez"],
    ["suivre","to follow","suis","suivons","suivez"],
    ["vendre","to sell","vends","vendons","vendez"],
    ["venir","to come","viens","venons","venez"],
    ["vouloir","to want","veuille","voulons","veuillez"],
    [" s'habiller","to get dressed","habille-toi","habillons-nous","habillez-vous"],
    ["s'aimer","to love each other","aime-toi","aimons-nous","aimez-vous"],
    ["s'amuser","to have fun","amuse-toi","amusons-nous","amusez-vous"],
    ["s'appeler","to be named","appelle-toi","appelons-nous","appelez-vous"],
    ["s'arrêter","to stop","arrête-toi","arrêtons-nous","arrêtez-vous"],
    ["se brosser","to brush","brosse-toi","brossons-nous","brossez-vous"],
    ["se confier","to confide","confie-toi","confions-nous","confiez-vous"],
    ["se coucher","to go to bed","couche-toi","couchons-nous","couchez-vous"],
    ["se débrouiller","to manage","débrouille-toi","débrouillons-nous","débrouillez-vous"],
    ["se dépêcher","to hurry","dépêche-toi","dépêchons-nous","dépêchez-vous"],
    ["se détendre","to relax","détends-toi","détendons-nous","détendez-vous"],
    ["se disputer","to argue","dispute-toi","disputons-nous","disputez-vous"],
    ["se fâcher","to get angry","fâche-toi","fâchons-nous","fâchez-vous"],
    ["se fiancer","to get engaged","fiance-toi","fiançons-nous","fiancez-vous"],
    ["se laver ","to wash oneself","lave-toi","lavons-nous","lavez-vous"],
    ["se lever","to get up","lève-toi","levons-nous","levez-vous"],
    ["se marier","to get married","marie-toi","marions-nous","mariez-vous"],
    ["se méfier","to distrust","méfie-toi","méfions-nous","méfiez-vous"],
    ["se peigner","to comb","peigne-toi","peignons-nous","peignez-vous"],
    ["se préparer","to get ready","prépare-toi","préparons-nous","préparez-vous"],
    ["se rappeler","to recall","rappelle-toi","rappelons-nous","rappelez-vous"],
    ["se raser","to shave","rase-toi","rasons-nous","rasez-vous"],
    ["se reposer","to relax","repose-toi","reposons-nous","reposez-vous"],
    ["se réveiller","to wake up","réveille-toi","réveillons-nous","réveilez-vous"],
    ["se souvenir","to remember","souviens-toi","souvenons-nous","souvenez-vous"],
    ["s'entendre","to get along","entends-toi","entendons-nous","entendez-vous"],
    ["s'habituer","to get used to","habitue-toi","habituons-nous","habituez-vous"],
    ["s'intéresser","to be interested in","intéresse-toi","intéressons-nous","intéressez-vous"],
    ["s'occuper","to take care of","occupe-toi","occupons-nous","occupez-vous"]
]

/*
    Put verbs per class here, order does NOT matter, it
    will just affect the order in which they are displayed 
    in the HTML.
*/ 
var verbs103 = [present]; // OLD AND USELESS
var verbs106 = [present, imparfait, passéComposé, imperatif];


var ERVerbs = [
    "abandonner",
    "acheter",
    "admirer",
    "adorer",
    "aider",
    "aimer",
    "ajouter",
    "appeler",
    "apporter",
    "arriver",
    "attraper",
    "augmenter",
    "bouger",
    "camper",
    "changer",
    "chanter",
    "chercher",
    "commander",
    "compter",
    "consulter",
    "continuer",
    "couper",
    "créer",
    "danser",
    "décider",
    "détester",
    "diminuer",
    "dîner",
    "donner",
    "échanger",
    "écouter",
    "embaucher",
    "embrasser",
    "emmener",
    "emprunter",
    "enseigner",
    "entrer",
    "essayer",
    "étudier",
    "éviter",
    "exiger",
    "expliquer",
    "fermer",
    "garder",
    "habiter",
    "indiquer",
    "inviter",
    "jouer",
    "laisser",
    "laver",
    "louer",
    "marcher",
    "monter",
    "nager",
    "naviguer",
    "nettoyer",
    "organiser",
    "oublier",
    "parler",
    "partager",
    "passer",
    "penser",
    "posséder",
    "préférer",
    "préparer",
    "profiter",
    "proposer",
    "quitter",
    "ranger",
    "réaliser",
    "remercier",
    "rentrer",
    "repousser",
    "réserver",
    "respecter",
    "rester",
    "retourner",
    "simplifier",
    "téléphoner",
    "tomber",
    "tourner",
    "travailler",
    "traverser",
    "trouver",
    "vider",
    
    "ER Verbs"
];

var ERIrreg = [
    "voyager",
    "manger",
    "ER Irregular"
]

var IRVerbs = [
    "accomplir", 
    "agir",
    "avertir",
    "choisir",
    "finir",
    "grandir",
    "grossir",
    "guérir",
    "maigrir",
    "obéir",
    "réagir",
    "réfléchir",
    "refroidir",
    "remplir",
    "réussir",
    "rougir",
    "vieillir",
    "IR Verbs"
];

var IRREGULARVerbs = [
    "admettre",
    "aller",
    "attendre",
    "avoir",
    "boire",
    "commettre",
    "comprendre",
    "connaître",
    "croire",
    "défendre",
    "descendre",
    "devenir",
    "devoir",
    "dormir",
    "écrire",
    "entendre",
    "envoyer",
    "espérer",
    "être",
    "faire",
    "mettre",
    "mourir",
    "naître",
    "partir",
    "perdre",
    "permettre",
    "pouvoir",
    "prendre",
    "promettre",
    "remettre",
    "rendre",
    "répondre",
    "revenir",
    "rire",
    "savoir",
    "sortir",
    "sourire",
    "suivre",
    "vendre",
    "venir",
    "vouloir",
    "Irregular Verbs"];

var groupList = [ERVerbs, IRVerbs, IRREGULARVerbs];


