/* My cheat sheet for making these 

EXCEL:
\"@\"

POWESHELL:
(get-content ".csv") | foreach {"[" + $_ } 
(get-content ".csv") | foreach { $_ + "]," } 


VERBS, tenses up here, lists for classes down there. 
First row col 1 is tense name, in the rest of the cols
Rest of the arrays are infinitif followed by conjugated 
verbs matching the pronounds in the first row
*/
var present = [
    ["présent","je","tu","il","nous","vous","ils","elles","elle"],
    ["aimer","aime","aimes","aime","aimons","aimez","aiment"],
    ["adorer","adore","adores","adore","adorons","adorez","adorent"],
    ["appeler","appelle","appelles","appelle","appelons","appelez","appellent"],
    ["chercher","cherche","cherches","cherche","cherchons","cherchez","cherchent"],
    ["coûter","coûte","coûtes","coûte","coûtons","coûtez","coûtent"],
    ["danser","danse","danses","danse","dansons","dansez","dansent"],
    ["détester","déteste","détestes","déteste","détestons","détestez","détestent"],
    ["donner","donne","donnes","donne","donnons","donnez","donnent"],
    ["écouter","écoute","écoutes","écoute","écoutons","écoutez","écoutent"],
    ["essayer","essaie","essaies","essaie","essayons","essayez","essaient"],
    ["étudier","étudie","étudies","étudie","étudions","étudiez","étudient"],
    ["habiter","habite","habites","habite","habitons","habitez","habitent"],
    ["inviter","invite","invites","invite","invitons","invitez","invitent"],
    ["manger","mange","manges","mange","mangeons","mangez","mangent"],
    ["marcher","marche","marches","marche","marchons","marchez","marchent"],
    ["nager","nage","nages","nage","nageons","nagez","nagent"],
    ["naviguer","navigue","navigues","navigue","naviguons","naviguez","naviguent"],
    ["parler","parle","parles","parle","parlons","parlez","parlent"],
    ["partager","partage","partages","partage","partageons","partagez","partagent"],
    ["penser","pense","penses","pense","pensons","pensez","pensent"],
    ["préférer","préfère","préfères","préfère","préférons","préférez","préfèrent"],
    ["rester","reste","restes","reste","restons","restez","restent"],
    ["téléphoner","téléphone","téléphones","téléphone","téléphonons","téléphonez","téléphonent"],
    ["travailler","travaille","travailles","travaille","travaillons","travaillez","travaillent"],
    ["trouver","trouve","trouves","trouve","trouvons","trouvez","trouvent"],
    ["voyager","voyage","voyages","voyage","voyageons","voyagez","voyagent"],
    ["être","suis","es","est","sommes","êtes","sont"],
    ["avoir","ai","as","a","avons","avez","ont"],
    ["chanter","chante","chantes","chante","chantons","chantez","chantent"],
    ["continuer","continue","continues","continue","continuons","continuez","continuent"],
    ["faire","fais","fais","fait","faisons","faites","font"],
    ["garder","garde","gardes","garde","gardons","gardez","gardent"],
    ["jouer","joue","joues","joue","jouons","jouez","jouent"],
    ["louer","loue","loues","loue","louons","louez","louent"],
    ["passer","passe","passes","passe","passons","passez","passent"],
    ["penser","pense","penses","pense","pensons","pensez","pensent"],
    ["préparer","prépare","prépares","prépare","préparons","préparez","préparent"],
    ["rentrer","rentre","rentres","rentre","rentrons","rentrez","rentrent"],
    ["aller","vais","vas","va","allons","allez","vont"],
    ["acheter","achète","achètes","achète","achetons","achetez","achètent"],
    ["fermer","ferme","fermes","ferme","fermons","fermez","ferment"],
    ["laisser","laisse","laisses","laisse","laissons","laissez","laissent"],
    ["réserver","réserve","réserves","réserve","réservons","réservez","réservent"],
    ["prendre","prends","prends","prend","prenons","prenez","prennent"],
    ["boire","bois","bois","boit","buvons","buvez","boivent"],
    ["ajouter","ajoute","ajoutes","ajoute","ajoutons","ajoutez","ajoutent"],
    ["commander","commande","commandes","commande","commandons","commandez","commandent"],
    ["couper","coupe","coupes","coupe","coupons","coupez","coupent"],
    ["laver","lave","laves","lave","lavons","lavez","lavent"],
    ["oublier","oublie","oublies","oublie","oublions","oubliez","oublient"],
    ["traverser","traverse","traverses","traverse","traversons","traversez","traversent"],
    ["tourner","tourne","tournes","tourne","tournons","tournez","tournent"],
    ["arriver","arrive","arrives","arrive","arrivons","arrivez","arrivent","blobs"],
    ["changer","change","changes","change","changeons","changez","changent"],
    ["emmener","emmène","emmènes","emmène","emmenons","emmenez","emmènent"],
    ["expliquer","explique","expliques","explique","expliquons","expliquez","expliquent"],
    ["indiquer","indique","indiques","indique","indiquons","indiquez","indiquent"],
    ["nettoyer","nettoie","nettoies","nettoie","nettoyons","nettoyez","nettoient"],
    ["posséder","possède","possèdes","possède","possédons","possédez","possèdent"],
    ["profiter","profite","profites","profite","profitons","profitez","profitent"],
    ["quitter","quitte","quittes","quitte","quittons","quittez","quittent"],
    ["ranger","range","ranges","range","rangeons","rangez","rangent"],
    ["simplifier","simplifie","simplifies","simplifie","simplifions","simplifiez","simplifient"],
    ["vider","vide","vides","vide","vidons","videz","vident"]
]

var imparfait = [
    ["imparfait","je","tu","il","nous","vous","ils"],
    ["aimer","aimais","aimais","aimait","aimions","aimiez","aimaient"],
    ["adorer","adorais","adorais","adorait","adorions","adoriez","adoraient"],
    ["appeler","appelais","appelais","appelait","appelions","appeliez","appellaient"],
    ["chercher","cherchais","cherchais","cherchait","cherchions","cherchiez","cherchaient"],
    ["danser","dansais","dansais","dansait","dansions","dansiez","dansaient"],
    ["détester","détestais","détestais","détestait","détestions","détestiez","détestaient"],
    ["donner","donnais","donnais","donnait","donnions","donniez","donnaient"],
    ["écouter","écoutais","écoutais","écoutait","écoutions","écoutiez","écoutaient"],
    ["essayer","essayais","essayais","essayait","essayions","essayiez","essayaient"],
    ["étudier","étudiais","étudiais","étudiait","étudiions","étudiiez","étudiaient"],
    ["habiter","habitais","habitais","habitait","habitions","habitiez","habitaient"],
    ["inviter","invitais","invitais","invitait","invitions","invitiez","invitaient"],
    ["manger","mangeais","mangeais","mangeait","mangeions","mangeiez","mangeaient"],
    ["marcher","marchais","marchais","marchait","marchions","marchiez","marchaient"],
    ["nager","nageais","nageais","nageait","nagions","nagiez","nageaient"],
    ["naviguer","naviguais","naviguais","naviguait","naviguions","naviguiez","naviguaient"],
    ["parler","parlais","parlais","parlait","parlions","parliez","parlaient"],
    ["partager","partageais","partageais","partageait","partagions","partagiez","partageaient"],
    ["penser","pensais","pensais","pensait","pensions","pensiez","pensaient"],
    ["préférer","préférais","préférais","préférait","préférions","préfériez","préféraient"],
    ["rester","restais","restais","restait","restions","restiez","restaient"],
    ["téléphoner","téléphonais","téléphonais","téléphonait","téléphonions","téléphoniez","téléphonaient"],
    ["travailler","travaillais","travaillais","travaillait","travaillions","travailliez","travaillaient"],
    ["trouver","trouvais","trouvais","trouvait","trouvions","trouviez","trouvaient"],
    ["voyager","voyageais","voyageais","voyageait","voyagions","voyagiez","voyageaient"],
    ["être","étais","étais","était","étions","étiez","étaient"],
    ["avoir","avais","avais","avait","avions","aviez","avaient"],
    ["chanter","chantais","chantais","chantait","chantions","chantiez","chantaient"],
    ["continuer","continuais","continuais","continuait","continuions","continuiez","continuaient"],
    ["faire","faisais","faisais","faisait","faisions","faisiez","faisaient"],
    ["garder","gardais","gardais","gardait","gardions","gardiez","gardaient"],
    ["jouer","jouais","jouais","jouait","jouions","jouiez","jouaient"],
    ["louer","louais","louais","louait","louions","louiez","louaient"],
    ["passer","passais","passais","passait","passions","passiez","passaient"],
    ["penser","pensais","pensais","pensait","pensions","pensiez","pensaient"],
    ["préparer","préparais","préparais","préparait","préparions","prépariez","préparaient"],
    ["rentrer","rentrais","rentrais","rentrait","rentrions","rentriez","rentraient"],
    ["aller","allais","allais","allait","allions","alliez","allaient"],
    ["acheter","achetais","achetais","achetait","achetions","achetiez","achetaient"],
    ["fermer","fermais","fermais","fermait","fermions","fermiez","fermaient"],
    ["laisser","laissais","laissais","laissait","laissions","laissiez","laissaient"],
    ["réserver","réservais","réservais","réservait","réservions","réserviez","réservaient"],
    ["prendre","prenais","prenais","prenait","prenions","preniez","prenaient"],
    ["boire","buvais","buvais","buvait","buvions","buviez","buvaient"],
    ["ajouter","ajoutais","ajoutais","ajoutait","ajoutions","ajoutiez","ajoutaient"],
    ["commander","commandais","commandais","commandait","commandions","commandiez","commandaient"],
    ["couper","coupais","coupais","coupait","coupions","coupiez","coupaient"],
    ["laver","lavais","lavais","lavait","lavions","laviez","lavaient"],
    ["oublier","oubliais","oubliais","oubliait","oubliions","oubliiez","oubliaient"],
    ["traverser","traversais","traversais","traversait","traversions","traversiez","traversaient"],
    ["tourner","tournais","tournais","tournait","tournions","tourniez","tournaient"],
    ["arriver","arrivais","arrivais","arrivait","arrivions","arriviez","arrivaient"],
    ["changer","changeais","changeais","changeait","changions","changiez","changeaient"],
    ["emmener","emmenais","emmenais","emmenait","emmenions","emmeniez","emmenaient"],
    ["expliquer","expliquais","expliquais","expliquait","expliquions","expliquiez","expliquaient"],
    ["indiquer","indiquais","indiquais","indiquait","indiquions","indiquiez","indiquaient"],
    ["nettoyer","nettoyais","nettoyais","nettoyait","nettoyions","nettoyiez","nettoyaient"],
    ["posséder","possédais","possédais","possédait","possédions","possédiez","possédaient"],
    ["profiter","profitais","profitais","profitait","profitions","profitiez","profitaient"],
    ["quitter","quittais","quittais","quittait","quittions","quittiez","quittaient"],
    ["ranger","rangeais","rangeais","rangeait","rangions","rangiez","rangeaient"],
    ["simplifier","simplifiais","simplifiais","simplifiait","simplifiions","simplifiiez","simplifiaient"],
    ["vider","vidais","vidais","vidait","vidions","vidiez","vidaient"]
];

var passéComposé = [
    ["Passé Composé","je","tu","il ","elle","nous","vous","ils","elles"],
    ["aimer","ai aimé","as aimé","a aimé","a aimé","avons aimé","avez aimé","ont aimé","ont aimé"],
    ["adorer","ai adoré","as adoré","a adoré","a adoré","avons adoré","avez adoré","ont adoré","ont adoré"],
    ["appeler","ai appelé","as appelé","a appelé","a appelé","avons appelé","avez appelé","ont appelé","ont appelé"],
    ["chercher","ai cherché","as cherché","a cherché","a cherché","avons cherché","avez cherché","ont cherché","ont cherché"],
    ["danser","ai dansé","as dansé","a dansé","a dansé","avons dansé","avez dansé","ont dansé","ont dansé"],
    ["détester","ai détesté","as détesté","a détesté","a détesté","avons détesté","avez détesté","ont détesté","ont détesté"],
    ["donner","ai donné","as donné","a donné","a donné","avons donné","avez donné","ont donné","ont donné"],
    ["écouter","ai écouté","as écouté","a écouté","a écouté","avons écouté","avez écouté","ont écouté","ont écouté"],
    ["essayer","ai essayé","as essayé","a essayé","a essayé","avons essayé","avez essayé","ont essayé","ont essayé"],
    ["étudier","ai étudié","as étudié","a étudié","a étudié","avons étudié","avez étudié","ont étudié","ont étudié"],
    ["habiter","ai habité","as habité","a habité","a habité","avons habité","avez habité","ont habité","ont habité"],
    ["inviter","ai invité","as invité","a invité","a invité","avons invité","avez invité","ont invité","ont invité"],
    ["manger","ai mangé","as mangé","a mangé","a mangé","avons mangé","avez mangé","ont mangé","ont mangé"],
    ["marcher","ai marché","as marché","a marché","a marché","avons marché","avez marché","ont marché","ont marché"],
    ["nager","ai nagé","as nagé","a nagé","a nagé","avons nagé","avez nagé","ont nagé","ont nagé"],
    ["naviguer","ai navigué","as navigué","a navigué","a navigué","avons navigué","avez navigué","ont navigué","ont navigué"],
    ["parler","ai parlé","as parlé","a parlé","a parlé","avons parlé","avez parlé","ont parlé","ont parlé"],
    ["partager","ai partagé","as partagé","a partagé","a partagé","avons partagé","avez partagé","ont partagé","ont partagé"],
    ["penser","ai pensé","as pensé","a pensé","a pensé","avons pensé","avez pensé","ont pensé","ont pensé"],
    ["préférer","ai préféré","as préféré","a préféré","a préféré","avons préféré","avez préféré","ont préféré","ont préféré"],
    ["téléphoner","ai téléphoné","as téléphoné","a téléphoné","a téléphoné","avons téléphoné","avez téléphoné","ont téléphoné","ont téléphoné"],
    ["travailler","ai travaillé","as travaillé","a travaillé","a travaillé","avons travaillé","avez travaillé","ont travaillé","ont travaillé"],
    ["trouver","ai trouvé","as trouvé","a trouvé","a trouvé","avons trouvé","avez trouvé","ont trouvé","ont trouvé"],
    ["voyager","ai voyagé","as voyagé","a voyagé","a voyagé","avons voyagé","avez voyagé","ont voyagé","ont voyagé"],
    ["être","ai été","as été","a été","a été","avons été","avez été","ont été","ont été"],
    ["avoir","ai eu","as eu","a eu","a eu","avons eu","avez eu","ont eu","ont eu"],
    ["chanter","ai chanté","as chanté","a chanté","a chanté","avons chanté","avez chanté","ont chanté","ont chanté"],
    ["continuer","ai continué","as continué","a continué","a continué","avons continué","avez continué","ont continué","ont continué"],
    ["faire","ai fait","as fait","a fait","a fait","avons fait","avez fait","ont fait","ont fait"],
    ["garder","ai gardé","as gardé","a gardé","a gardé","avons gardé","avez gardé","ont gardé","ont gardé"],
    ["jouer","ai joué","as joué","a joué","a joué","avons joué","avez joué","ont joué","ont joué"],
    ["louer","ai loué","as loué","a loué","a loué","avons loué","avez loué","ont loué","ont loué"],
    ["passer","ai passé","as passé","a passé","a passé","avons passé","avez passé","ont passé","ont passé"],
    ["penser","ai pensé","as pensé","a pensé","a pensé","avons pensé","avez pensé","ont pensé","ont pensé"],
    ["préparer","ai préparé","as préparé","a préparé","a préparé","avons préparé","avez préparé","ont préparé","ont préparé"],
    ["acheter","ai acheté","as acheté","a acheté","a acheté","avons acheté","avez acheté","ont acheté","ont acheté"],
    ["fermer","ai fermé","as fermé","a fermé","a fermé","avons fermé","avez fermé","ont fermé","ont fermé"],
    ["laisser","ai laissé","as laissé","a laissé","a laissé","avons laissé","avez laissé","ont laissé","ont laissé"],
    ["réserver","ai réservé","as réservé","a réservé","a réservé","avons réservé","avez réservé","ont réservé","ont réservé"],
    ["prendre","ai pris","as pris","a pris","a pris","avons pris","avez pris","ont pris","ont pris"],
    ["boire","ai bu","as bu","a bu","a bu","avons bu","avez bu","ont bu","ont bu"],
    ["ajouter","ai ajouté","as ajouté","a ajouté","a ajouté","avons ajouté","avez ajouté","ont ajouté","ont ajouté"],
    ["commander","ai commandé","as commandé","a commandé","a commandé","avons commandé","avez commandé","ont commandé","ont commandé"],
    ["couper","ai coupé","as coupé","a coupé","a coupé","avons coupé","avez coupé","ont coupé","ont coupé"],
    ["laver","ai lavé","as lavé","a lavé","a lavé","avons lavé","avez lavé","ont lavé","ont lavé"],
    ["oublier","ai oublié","as oublié","a oublié","a oublié","avons oublié","avez oublié","ont oublié","ont oublié"],
    ["traverser","ai traversé","as traversé","a traversé","a traversé","avons traversé","avez traversé","ont traversé","ont traversé"],
    ["tourner","ai tourné","as tourné","a tourné","a tourné","avons tourné","avez tourné","ont tourné","ont tourné"],
    ["changer","ai changé","as changé","a changé","a changé","avons changé","avez changé","ont changé","ont changé"],
    ["emmener","ai emmené","as emmené","a emmené","a emmené","avons emmené","avez emmené","ont emmené","ont emmené"],
    ["expliquer","ai expliqué","as expliqué","a expliqué","a expliqué","avons expliqué","avez expliqué","ont expliqué","ont expliqué"],
    ["indiquer","ai indiqué","as indiqué","a indiqué","a indiqué","avons indiqué","avez indiqué","ont indiqué","ont indiqué"],
    ["nettoyer","ai nettoyé","as nettoyé","a nettoyé","a nettoyé","avons nettoyé","avez nettoyé","ont nettoyé","ont nettoyé"],
    ["posséder","ai possédé","as possédé","a possédé","a possédé","avons possédé","avez possédé","ont possédé","ont possédé"],
    ["profiter","ai profité","as profité","a profité","a profité","avons profité","avez profité","ont profité","ont profité"],
    ["quitter","ai quitté","as quitté","a quitté","a quitté","avons quitté","avez quitté","ont quitté","ont quitté"],
    ["ranger","ai rangé","as rangé","a rangé","a rangé","avons rangé","avez rangé","ont rangé","ont rangé"],
    ["simplifier","ai simplifié","as simplifié","a simplifié","a simplifié","avons simplifié","avez simplifié","ont simplifié","ont simplifié"],
    ["vider","ai vidé","as vidé","a vidé","a vidé","avons vidé","avez vidé","ont vidé","ont vidé"],
    ["rester","ai resté","es resté","est resté","est restée","sommes restés","êtes restés","sont restés","sont restées"],
    ["arriver","suis arrivé","es arrivé","est arrivé","est arrivée","sommes arrivés","êtes arrivés","sont arrivés","sont arrivées"],
    ["aller","suis allé","es allé","est allé","est allée","sommes allés","êtes allés","sont allés","sont allées"],
    ["rentrer","suis rentré","es rentré","est rentré","est rentrée","sommes rentrés","êtes rentrés","sont rentrés","sont rentrées"],
];

var imperatif = [
    ["Impératif","(tu)","(nous)","(vous)"],
    ["aimer","aime","aimons","aimez"],
    ["adorer","adore","adorons","adorez"],
    ["appeler","appelle","appelons","appellez"],
    ["chercher","cherche","cherchons","cherchez"],
    ["danser","danse","dansons","dansez"],
    ["détester","déteste","détestons","détestez"],
    ["donner","donne","donnons","donnez"],
    ["écouter","écoute","écoutons","écoutez"],
    ["essayer","essaie","essayons","essayez"],
    ["étudier","étudie","étudions","étudiez"],
    ["habiter","habite","habitons","habitez"],
    ["inviter","invite","invitons","invitez"],
    ["manger","mange","mangons","mangez"],
    ["marcher","marche","marchons","marchez"],
    ["nager","nage","nageons","nagez"],
    ["naviguer","navigue","naviguons","naviguez"],
    ["parler","parle","parlons","parlez"],
    ["partager","partage","partageons","partagez"],
    ["penser","pense","pensons","pensez"],
    ["préférer","préfère","préférons","préférez"],
    ["rester","reste","restons","restez"],
    ["téléphoner","téléphone","téléphonons","téléphonez"],
    ["travailler","travaille","travaillons","travaillez"],
    ["trouver","trouve","trouvons","trouvez"],
    ["voyager","voyage","voyageons","voyagez"],
    ["être","sois","soyons","soyez"],
    ["avoir","aie","ayons","ayez"],
    ["chanter","chante","chantons","chantez"],
    ["continuer","continue","continuons","continuez"],
    ["faire","fais","faisons","faites"],
    ["garder","garde","gardons","gardez"],
    ["jouer","joue","jouons","jouez"],
    ["louer","loue","louons","louez"],
    ["passer","passe","passons","passez"],
    ["penser","pense","pensons","pensez"],
    ["préparer","prépare","préparons","préparez"],
    ["rentrer","rentre","rentrons","rentrez"],
    ["aller","va","allons","allez"],
    ["acheter","achète","achetons","achetez"],
    ["fermer","ferme","fermons","fermez"],
    ["laisser","laisse","laissons","laissez"],
    ["réserver","réserve","réservons","réservez"],
    ["prendre","prends","prenons","prenez"],
    ["boire","bois","buvons","buvez"],
    ["ajouter","ajoute","ajoutons","ajoutez"],
    ["commander","commande","commandons","commandez"],
    ["couper","coupe","coupons","coupez"],
    ["laver","lave","lavons","lavez"],
    ["oublier","oublie","oublions","oubliez"],
    ["traverser","traverse","traversons","traversez"],
    ["tourner","tourne","tournons","tournez"],
    ["arriver","arrive","arrivons","arrivez"],
    ["changer","change","changeons","changez"],
    ["emmener","emmène","emmenons","emmenez"],
    ["expliquer","explique","expliquons","expliquez"],
    ["indiquer","indique","indiquons","indiquez"],
    ["nettoyer","nettoie","nettoyons","nettoyez"],
    ["posséder","possède","possédons","possédez"],
    ["profiter","profite","profitons","profitez"],
    ["quitter","quitte","quittons","quittez"],
    ["ranger","range","rangons","rangez"],
    ["simplifier","simplifie","simplifions","simplifiez"],
    ["vider","vide","vidons","videz"]
]

/*
    Put verbs per class here, order does NOT matter, it
    will just affect the order in which they are displayed 
    in the HTML.
*/ 
var verbs103 = [present];
var verbs106 = [present, imparfait, passéComposé, imperatif];


var ERVerbs = ["manger", "rentrer", "passer"];
var IRVerbs = ["aimer", "adorer", "appeler"];
var IRREGULARVerbs = ["nettoyer", "simplifier"];

var groupList = [ERVerbs, IRVerbs, IRREGULARVerbs];


